import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "./_providers/Authprovider";
import SocketProvider from "./_providers/SocketProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html lang="en">
            <body className="bg-amber-50">
                <AuthProvider>
                    <SocketProvider>{children}</SocketProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
